### ISSUE TITLE
Per-object defined properties overwritten by default tile properties (defined in tileset)

### ISSUE THREAD

**Issue by Powalski** [bitcraft/PyTMX#107]
Hello,

I have an object layer in Tiled where some of my objects are based on tiles. These tiles have custom properties defined in my tileset, and I can overwrite their default values for each tile object in the object layer.
However when I load the tileset with pytmx, the default values always overwrite the per-object defined values. I think it occurs in `TiledMap.parse_xml` :
```
for o in [o for o in self.objects if o.gid]:

    # gids might also have properties assigned to them
    # in that case, assign the gid properties to the object as well
    p = self.get_tile_properties_by_gid(o.gid)
    if p:
        o.properties.update(p)  # <-- here
...
return self
```

Is this the intented behaviour or is it a bug?

**Comment by Powalski** [comment]
I don't know if this what you mean by 'spec', but in the Tiled docs, there is a section about [Tile Property Inheritance](https://doc.mapeditor.org/en/stable/manual/custom-properties/#tile-property-inheritance) ; I think it covers my problem, although I don't use Typed Tiles.
I'm sorry if this wasn't clear in my original message : I am not saying that Layer Properties should override Tile Properties, but that the properties of an tile object instance should override the tile properties defined in the tileset - e.g. if I have a 'Star' tile, I want to be able to set a custom property 'points earned' to 5 in the tileset, place seven stars in an object layer, and change the 'points earned' value to 8 for one star. The result should be six stars with value 5 and one with value 8.

**Comment by bitcraft** [comment]
Sure, I see what you are saying now.  The link was really helpful.  The part of the code you linked is the right spot.  `update` should be changed to `setdefault` and i think it would work as expected.  Unfortunately, I don't have much time to test, but I would happily take a PR if you are able to open one.

**Comment by bitcraft** [comment]
Hahaha, ok yeah you are right.  This was fixed in the past.  I have updated the pip version and you should have it working as expected.  Please let me know if it works for you and we can close the ticket.  :grin:

**Comment by Powalski** [comment]
Unfortunately it still doesn't work, I have done `pip uninstall pytmx` followed by `pip install pytmx` but the code is still the same.

**Comment by bitcraft** [comment]
For whatever reason, pypi was accepting new uploads, but it was not reflecting on the website.  I had to change to another tool to upload it.  I've verified that the "setdefault" change is in there.  Feel free to test again.

**Comment by Powalski** [comment]
This works fine now thanks!
