### ISSUE TITLE
Tiled 1.0 and "map version"

### ISSUE THREAD

**Issue by Remusforte** [bitcraft/PyTMX#83]
In Tiled 1.0, Bjorn has changed the "map version"  parameter from a string of a float to a string of a serial number which he eventually wants to define based on the release build (an example might be: "2017.06.11a". 

This parameter is typically in line 2 of the .tmx file. Unfortunately, PyTMX is parsing this line and trying to convert that string into a float, which as of Tiled 1.0 instantly crashes Python, as it is no longer a valid floating point number.

Example of new Tiled 1.0 .tmx line showing the change in format for this parameter:
`map version="1.0.0" orientation="hexagonal" renderorder="right-down" width="30" height="30" tilewidth="100" tileheight="86" hexsidelength="50" staggeraxis="x" staggerindex="odd" nextobjectid="1"`

Bjorn has agreed to revert back to a float for now, but ideally PyTMX should **not** be reading in the "map version" parameter as a float. There is really no reason to assume it will be a number, so I suggest the PyTMX parser be updated to grab this parameter and leave it exactly as stored in the .tmx file: a string.

**Comment by bjorn** [comment]
Was already addressed in 64112ca7c9957a06b7d309e209228c66c63fbde2. I guess @Remusforte would appreciate a version bumb. :-)

Though as indicated, I will revert this change in Tiled 1.0.1 and store the specific version in a new `tiledversion` attribute, but it anyway doesn't hurt not to parse this attribute as a float.

**Comment by Remusforte** [comment]
Hmmm, I'll recheck. I installed the most recent update PyTMX *yesterday* and my code still crashed on reading the .tmx file (for invalid float error on this param). Let me look harder.

**Comment by bitcraft** [comment]
I think that I have changed it to a string, but maybe haven't updated pypi
yet. Thanks for the detailed history of the issue with Tiled 1.0.

**Comment by Remusforte** [comment]
@bitcraft: Did you release the update which includes this fix for Tiled 1.0?

I've tried: "pip install pytmx --upgrade" a few times, and I'm still not getting any updates in.

I did manually change the affected line in my local copy, but we have a team that needs to convert over, and I'm hoping to give them a pip command to upgrade automatically. Possible?

**Comment by bjorn** [comment]
@Remusforte Just to note, I've in the meantime published the Tiled 1.0.1 release so installing this update should be the quickest way to avoid these issues.

**Comment by bitcraft** [comment]
ive pushed a change that will handle the version as a string.  changes are in pypi as well.

**Comment by bjorn** [comment]
@bitcraft Cool! Just to note, I've also just updated the [TMX Map Format](http://doc.mapeditor.org/reference/tmx-map-format/) page and the [changelog](http://doc.mapeditor.org/reference/tmx-changelog/), so you can check if you still need to add anything regarding the Tiled 1.0 release in general.

**Comment by bitcraft** [comment]
Thank you @bjorn!  I'll check out that page again.  I remember spending hours on it when I first wrote pytmx.

**Comment by bitcraft** [comment]
@Remusforte has this resolved your issue?

**Comment by Remusforte** [comment]
@bitcraft: Yes, pip ... --upgrade pulled in your release, and I see the string designation in there. Works perfectly now! Thanks for fixing and sending out!

@bjorn: Thanks also for Tiled 1.0.1; I pulled in that update this morning. Works perfectly.

Thanks for the help on this one. A win-win, as that field can now be flexibly used for whatever version coding system you might imagine in the future. :-)
